# Generated by Django 2.2.7 on 2019-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_name',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
