# Generated by Django 2.2.7 on 2019-11-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mark_student_studentclass_studyyear_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.Student'),
        ),
    ]
