# Generated by Django 2.2.7 on 2019-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191118_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_classes', models.ManyToManyField(to='core.StudentClass')),
            ],
        ),
    ]
