# Generated by Django 2.2.7 on 2019-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_teaching_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teaching_subjects',
            field=models.ManyToManyField(to='core.TeacherSubject'),
        ),
    ]
